### ISSUE TITLE
Sweep CLI API for inconsistencies before v1.0

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1430]
**What design is being proposed?**
Some of our flags evolved over time and are inconsistent. Our last chance to fix that is before the v1.0 release. Let's look at our entire flag and command set, and create a PEP for any changes.

For example, here are some confusing flags

* Specify a credential set, `--cred|c`
* Specify a parameter set, `--parameter-set|p`
* Specify a parameter key=value pair, `--param KEY=VALUE`

We should change it to the following to be more consistent:

`--credential-set|c`, `--parameter-set|p`, `--param`

I think we can use a trick in cobra to have this not be a breaking change and support --cred and --credential set. https://stackoverflow.com/a/67929738

# Task Roundup
- [x] Rename --cred to --credential-set
- [x] Allow reference as a positional argument to explain|inspect
- [x] Move porter bundle install|upgrade|invoke|uninstall to porter installation VERB, keeping the shortened aliases.

**Comment by carolynvs** [comment]
Another inconsistency which was introduced after we settled on adding an installation command. Some commands related to installations are under the bundle resources in the CLI

```
$ porter bundle --help
Commands for working with bundles. These all have shortcuts so that you can call these commands without the bundle resource prefix. For example, porter bundle install is available as porter install as well.

Usage:
  porter bundles [command]

Aliases:
  bundles, bundle

Commands:
  archive     Archive a bundle from a reference
  build       Build a bundle
  copy        Copy a bundle
  create      Create a bundle
  explain     Explain a bundle
  inspect     Inspect a bundle
  install     Create a new installation of a bundle
  invoke      Invoke a custom action on an installation
  lint        Lint a bundle
  uninstall   Uninstall an installation
  upgrade     Upgrade an installation
```

The following commands should be moved under installation:
* porter installation create  (aliased to porter install)
* porter installation upgrade (aliased to porter upgrade)
* porter installation uninstall (aliased to porter uninstall)
* porter installation invoke (aliased to porter invoke)

porter bundle install should stay the same since it's operating on a bundle, not an existing installation.

Thinking ahead to other bundle commands that we want ([like bundle list](https://github.com/carolynvs/porter-proposals/blob/dependencies-labels-namespaces/pep/003-dependency-namespaces-and-labels.md#porter-bundle-index)), I was looking at explain. I think it should stay the same allowing room for a `porter bundle show REPOSITORY` and you can see information about the bundle and how its being used in your environment.

**Comment by carolynvs** [comment]
Petition to change the explain and inspect to use positional arguments

```
$ porter explain REFERENCE
$ porter inspect REFERENCE
``

Normally the positional argument is a unique value that is being acted upon by the command (the object of the sentence). In other commands we use --reference because the bundle isn't being acted upon, it's just tweaking the command (e.g. `porter install NAME --reference REFERENCE`. With these two commands, we are acting up on the bundle directly though, so the flag is not necessary.

**Comment by joshuabezaleel** [comment]
@carolynvs May I give a try on this one? I think I can work on the two already mentioned issues above (https://github.com/getporter/porter/issues/1430#issuecomment-854158219 and https://github.com/getporter/porter/issues/1430#issuecomment-860863202). Do we need to still check for other inconsistencies?

**Comment by carolynvs** [comment]
This issue isn't ready to do yet as we still have lots more review and discussion ahead of us. The first thing that we want to do is evaluate any irregularities in the commands, and list them here with suggested fixes. Then maintainers can agree on which way we would like to fix them. Even my initial ideas in these comments are unvetted and need more thought!

For example, do we want a --cred flag that let's you specify a credential at the command line, to be in line with parameters? Or when I suggested that we shuffle those installation commands, there wasn't another idea for how to use the `porter installation create` command (which in #1787 I had a different idea for). This issue is our last chance to make sure that we don't make more inconsistencies. 😀 

What we can use help with is just identifying more places in our CLI where we aren't consistent, or the command is awkward, and calling them out here. If you'd like to look over Porter's commands, and find more goofs, that will help!
