### ISSUE TITLE
Apply to CNCF Incubation stage

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1951]
Let's figure out what we need before we can apply to the CNCF Incubating stage:

https://github.com/cncf/toc/blob/main/process/graduation_criteria.adoc#incubating-stage

- [ ] #2342
- [x] #2343
- [x] Substantial ongoing flow of commits and merged contributions
- [x] Clear versioning scheme
- [x] #2341
- [ ] Get OpenSSF badge 
- [ ] Get security assessment
- [ ] Prep for the [due diligence process](https://github.com/cncf/toc/blob/main/process/due-diligence-guidelines.md)

**Comment by schristoff** [comment]
#3149
