### ISSUE TITLE
Make release/v1 the default branch

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2180]
We need to make release/v1 the default branch in github so that pull requests target it automatically, and when people go to the repo, they see our most recent code by default.

- [x] Switch the default branch
- [x] Make sure branch protection rules are right for it still
- [x] Sweep docs for anything that may need to be updated because of the switch

**Comment by carolynvs** [comment]
Done!
