### ISSUE TITLE
v1 go live

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2288]
This is a task list for everything we need to do in release our final v1.0.0 release:

- [x] Merge main into v0 if there has been new commits. Right now netlify builds the v0 branch and hosts at v0.getporter.org. This is the long term branch for v0, from which any hotfixes will be merged into and tagged from.
- [x] Merge release/v1 into main, resolving all conflicts using release/v1 (use the git flags for this, don't attempt to do it manually) and push to main. Double check that the entire repo contents of main exactly match the repo contents of 1.0.0-rc.3. This isn't really a merge so much as a force reset to make main match 1.0.0-rc.3
    ```
    git checkout main
    git pull
    git fetch upstream release/v1:release/v1
    git merge -X theirs release/v1 # merge and use v1 when there's a conflict
    git diff main..release/v1 # verify that they are exactly the same!
    git push upstream main:main # will need to turn off branch protection for admins to do this
    # wait for a passing canary build
    ```
- [x] Tag v1.0.0-rc for release candidate once all code changes are merged
- [x] Update operator to use the release candidate
- [x]  Wait for feedback on the release candidate and fix any issues that's reported
- [x] Tag v1.0.0 from main (so that latest is now the most recent tagged v1 release). Again 1.0.0-rc.3 should exactly match what we are tagging with v1.0.0
    ```
    # wait for the canary build to pass after merging release/v1 into main
    git tag v1.0.0 -f -am "" v1.0.0-rc.3^{} # add a tag to v1.0.0-rc.3 for v1.0.0
    git difftool v1.0.0-rc.3..v1.0.0 # they should be the same!
    git push upstream v1.0.0 # this essentially rebuilds v1.0.0-rc.3 as v1.0.0 (it excludes recent changes to release/v1 which are all doc changes)
    ```
- [x] Document which mixins and plugins are compatible with which versions when you upgrade. You MUST upgrade plugins, but mixins don't have to be. We recommend grabbing the 1.0 versions of the mixins if available since they have improvements.
- [x] Ensure that all pending mixin changes have been applied to the mixins (e.g. configuration schema)
- [ ] Tag v1.0.0 for porter maintained mixins/plugins when we are sure they have been vetted properly
- [x] Change the default branch to main in github so that new PRs go to main again
- [x] Sweep the site for mention of release/v1, for example in the contributing guide, and update as appropriate to point people to main.
- [x] Update the install instructions to reference 1.0.0 and remove mention of the pre-release.
- [x] We had a page about how the v1 release would work that we can remove too
- [x] Blog post to announce v1. Introduce people to porter and summarize what has changed since v0.38

There is more, this is just the initial attempt at listing all the tasks
