### ISSUE TITLE
Consolidate docker/registry libraries as much as possible

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2299]
Porter has ended up having to use a BUNCH of different libraries to accomplish what feels like the same task thanks to how we pulled in existing implementations from cnab-go, duffle, and other efforts at the time we began working on CNAB. Now that storing artifacts in OCI registries is not new, I think we may be able to heavily consolidate this list down to 1-2 libraries, ideally without a dependency on containerd since that is a pain to keep up with security/patch wise.

* cnabio/cnab-to-oci
* pivotal/image-relocation
* docker and moby libraries
* go-container-registry
* containerd
* crane

## TODO
- [ ] determine which porter commands and call paths depend on each library
- [ ] determine which underlying library that each of these depend upon (e.g. crane uses go-container-registry). Find overlap between our common transitive dependencies.
- [ ] Fill out the issue below as we figure out what is used, where and what can be consolidated.

## Crane

We use crane to list tags for a repository in a registry (used by dependencies). At the time when I added that I'm not sure why I didn't use go-container-registry, but I think it does now support what we need and this can be eliminated.

## Image Relocation

- [ ] Understand if the image relocation library has any bundle specific logic or functionality that cannot be replicated with an existing library such as go-container-registry.
- [ ] Understand what parts of cnab-go use image-relocation and remove or swap that dependency

## CNAB to OCI

- [ ] Understand what libraries cnab-to-oci depends upon and if we are reimplementing any functionality in those libraries unnecessarily (we use a lot of low-level resolver and push/pull functionality that I wonder if its necessary or if we can use a the dependency directly for more functionality).
