### ISSUE TITLE
Update our maintainer list

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2343]
In order to apply for CNCF Incubation stage, per the TOC we need "a healthy number of maintainers", people who have commit rights.

- [ ] Identify maintainers who have not participated for 6 months and promote to emeritus status
- [ ] Identify maintainers for sub-repos and make sure they are called out as maintainers for the project too.
- [ ] Update the maintainers and owners files to reflect currently active maintainers

**Comment by schristoff** [comment]
I don't think so

**Comment by schristoff** [comment]
It is now
