### ISSUE TITLE
Update to Go 1.19 in all repositories

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2415]
Now that we are done stabilizing, let's bump go to the most recent patch of 1.19. This will allow us to try out generics later.

- [x] skeletor
- [x] magefiles -> v0.3.3
- [x] az mixin, v1.0.0-rc.2 because I merged a feature too (setting the client version)
- [x] azure plugin -> v1.0.1
- [x] terraform mixin -> v1.0.0-rc.2 because I added mixin config to the schema
- [x] hashicorp plugin -> v1.0.0
- [x] k8s mixin -> v1.0.0
- [ ] k8s plugin
- [x] docker mixin -> v1.0.0
- [x] docker-compose mixin -> v1.0.0
- [x] arm mixin -> v1.0.0
- [x] aws mixin -> v1.0.0
- [x] gcloud mixin -> v1.0.0
- [x] helm3 mixin -> v1.0.0
- [ ] operator
