### ISSUE TITLE
Epic: Porter Retro Recap

### ISSUE THREAD

**Issue by schristoff** [getporter/porter#2874]
On 8.16 we had a Porter Retro to see where we could do better. This is a main issue to track these tasks we set out to achieve. 

These four issues fall into two main focuses, "Product Fit and User Story" and "Product Planning and Community Development"

*Product Fit and User Story* #2875 
- [ ] We will work on customer development to determine product fit / direction.
- [ ] We will create a user story for the prime use case for Porter.

*Product Planning and Community Development* #2876
- [ ] We will start having a monthly Porter user office hours specifically to help users with questions.
- [ ]  We will plan Porter's next big release and build a shared vision of what that release will focus on.
