### ISSUE TITLE
Epic: Support build-time credential injection

### ISSUE THREAD

**Issue by vdice** [getporter/porter#959]
There are use cases where Porter authors would like a way to inject credentials at build-time (rather than the currently supported run-time injection).  For instance, if a mixin supports extended configuration and this configuration may need credentials to run.  (See https://github.com/deislabs/porter-helm/pull/61 for an example)

To enable this, we'd need the following features added:

- [ ] Porter build takes an optional credential set, `porter build -c cred`
- [ ] Credentials in a Porter manifest can be designated build-only, such that they are not included into the resulting bundle but are available to inject into build-time config.  For example:

    ```yaml
    credentials:
      - name: repo-username
        # credential is only available at buildtime
        buildtime: true 
        default: bobby-tables
    ```
- [ ] Build-only credentials in a Porter manifest can be interpolated (via `{{ build.credentials.mybuildcred }}`) in build-time config (for instance, mixin config).  Note: here we use `build.credentials` vs `bundle.credentials` to distinguish build-only from bundle.

**Comment by carolynvs** [comment]
Closing and tracking under #1769
