### ISSUE TITLE
Epic: Install mixins defined in bundle

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#975]
Installing mixins by hand works great but really is just the plumbing to support this next epic. Letting the bundle author specify which mixins a bundle requires:

```yaml
mixins:
- helm:
     mixin:
       url: https://mchorfa.github.com/porter-helm3/atom.xml
       version: ~v0.1.3
```

During `porter build` or `porter install|upgrade|uninstall` if the local installation of Porter does not have the desired mixin source and version (allowing for fuzzy version selection) installed, it is automatically installed before the bundle is built or executed. 

The client has control over:
* whether automatic installation is enabled using our standard config file, env and flag
* allow/deny list for both sources
* allow/deny list for individual mixins
* preferred source for mixins when the author did not specify one, by default it is our atom feed

These need to be broken down into individual issues, and collected into a milestone:
- [ ] installation of mixins needs to change to allow for multiple versions installed at a time
- [ ] listing mixins needs to change to support have a better design considering potential non-contiguous versions and multiple sources and authors. This may require a completely different set of data displayed for list and new commands to support list.
- [ ] mixin uninstall needs extra flags to know which one it is uninstalling, including all of them
- [ ] porter's mixin interface needs a way to select which mixin it is querying based on the current manifest.
- [ ] porter build needs to select the correct binaries to copy into the invocation image
- [ ] porter build should be updated to use a lockfile to track the resolved mixin versions.

Per https://github.com/getporter/porter/discussions/1311 an interesting implementation idea would be to install mixins globally, but before the build executes, copy the relevant mixins into the bundle's .cnab directory and then execute the mixins from there. Basically change resolution of the client mixin path from the PORTER_HOME to BUNDLE_DIR, which would isolate the mixin execution from having to be version aware.

**Comment by RichiCoder1** [comment]
This boat may have sailed, but a terraform-like experience where mixins are defined in the `yaml` and then an init command managed pulling them to a bundle-temp dir would be great. Would simplify management and caching too.
